/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as ApiSharesRouteImport } from './routes/api/shares'
import { Route as ApiOpenrouterTestRouteImport } from './routes/api/openrouter-test'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedStudyRouteImport } from './routes/_authenticated/study'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProductivityRouteImport } from './routes/_authenticated/productivity'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated/learn'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBoardsRouteImport } from './routes/_authenticated/boards'
import { Route as ApiSharesTokenRouteImport } from './routes/api/shares/$token'
import { Route as ApiSharedTokenRouteImport } from './routes/api/shared/$token'
import { Route as ApiLearningWhiteboardRouteImport } from './routes/api/learning/whiteboard'
import { Route as ApiLearningVoiceRouteImport } from './routes/api/learning/voice'
import { Route as ApiLearningSessionRouteImport } from './routes/api/learning/session'
import { Route as ApiLearningRevisionRouteImport } from './routes/api/learning/revision'
import { Route as ApiLearningOcrRouteImport } from './routes/api/learning/ocr'
import { Route as ApiLearningNotesRouteImport } from './routes/api/learning/notes'
import { Route as ApiLearningMemoryRouteImport } from './routes/api/learning/memory'
import { Route as ApiLearningGoalsRouteImport } from './routes/api/learning/goals'
import { Route as ApiLearningFlashcardsRouteImport } from './routes/api/learning/flashcards'
import { Route as ApiLearningFeaturesRouteImport } from './routes/api/learning/features'
import { Route as ApiLearningAnalyticsRouteImport } from './routes/api/learning/analytics'
import { Route as ApiLearningSourcesIngestRouteImport } from './routes/api/learning/sources/ingest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharesRoute = ApiSharesRouteImport.update({
  id: '/api/shares',
  path: '/api/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterTestRoute = ApiOpenrouterTestRouteImport.update({
  id: '/api/openrouter-test',
  path: '/api/openrouter-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyRoute = AuthenticatedStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductivityRoute =
  AuthenticatedProductivityRouteImport.update({
    id: '/productivity',
    path: '/productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardsRoute = AuthenticatedBoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSharesTokenRoute = ApiSharesTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => ApiSharesRoute,
} as any)
const ApiSharedTokenRoute = ApiSharedTokenRouteImport.update({
  id: '/api/shared/$token',
  path: '/api/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningWhiteboardRoute = ApiLearningWhiteboardRouteImport.update({
  id: '/api/learning/whiteboard',
  path: '/api/learning/whiteboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningVoiceRoute = ApiLearningVoiceRouteImport.update({
  id: '/api/learning/voice',
  path: '/api/learning/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningSessionRoute = ApiLearningSessionRouteImport.update({
  id: '/api/learning/session',
  path: '/api/learning/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningRevisionRoute = ApiLearningRevisionRouteImport.update({
  id: '/api/learning/revision',
  path: '/api/learning/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningOcrRoute = ApiLearningOcrRouteImport.update({
  id: '/api/learning/ocr',
  path: '/api/learning/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningNotesRoute = ApiLearningNotesRouteImport.update({
  id: '/api/learning/notes',
  path: '/api/learning/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningMemoryRoute = ApiLearningMemoryRouteImport.update({
  id: '/api/learning/memory',
  path: '/api/learning/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningGoalsRoute = ApiLearningGoalsRouteImport.update({
  id: '/api/learning/goals',
  path: '/api/learning/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningFlashcardsRoute = ApiLearningFlashcardsRouteImport.update({
  id: '/api/learning/flashcards',
  path: '/api/learning/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningFeaturesRoute = ApiLearningFeaturesRouteImport.update({
  id: '/api/learning/features',
  path: '/api/learning/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningAnalyticsRoute = ApiLearningAnalyticsRouteImport.update({
  id: '/api/learning/analytics',
  path: '/api/learning/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLearningSourcesIngestRoute =
  ApiLearningSourcesIngestRouteImport.update({
    id: '/api/learning/sources/ingest',
    path: '/api/learning/sources/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/boards': typeof AuthenticatedBoardsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openrouter-test': typeof ApiOpenrouterTestRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/api/learning/analytics': typeof ApiLearningAnalyticsRoute
  '/api/learning/features': typeof ApiLearningFeaturesRoute
  '/api/learning/flashcards': typeof ApiLearningFlashcardsRoute
  '/api/learning/goals': typeof ApiLearningGoalsRoute
  '/api/learning/memory': typeof ApiLearningMemoryRoute
  '/api/learning/notes': typeof ApiLearningNotesRoute
  '/api/learning/ocr': typeof ApiLearningOcrRoute
  '/api/learning/revision': typeof ApiLearningRevisionRoute
  '/api/learning/session': typeof ApiLearningSessionRoute
  '/api/learning/voice': typeof ApiLearningVoiceRoute
  '/api/learning/whiteboard': typeof ApiLearningWhiteboardRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/learning/sources/ingest': typeof ApiLearningSourcesIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/boards': typeof AuthenticatedBoardsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/study': typeof AuthenticatedStudyRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openrouter-test': typeof ApiOpenrouterTestRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/api/learning/analytics': typeof ApiLearningAnalyticsRoute
  '/api/learning/features': typeof ApiLearningFeaturesRoute
  '/api/learning/flashcards': typeof ApiLearningFlashcardsRoute
  '/api/learning/goals': typeof ApiLearningGoalsRoute
  '/api/learning/memory': typeof ApiLearningMemoryRoute
  '/api/learning/notes': typeof ApiLearningNotesRoute
  '/api/learning/ocr': typeof ApiLearningOcrRoute
  '/api/learning/revision': typeof ApiLearningRevisionRoute
  '/api/learning/session': typeof ApiLearningSessionRoute
  '/api/learning/voice': typeof ApiLearningVoiceRoute
  '/api/learning/whiteboard': typeof ApiLearningWhiteboardRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/learning/sources/ingest': typeof ApiLearningSourcesIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/boards': typeof AuthenticatedBoardsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/productivity': typeof AuthenticatedProductivityRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/study': typeof AuthenticatedStudyRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/openrouter-test': typeof ApiOpenrouterTestRoute
  '/api/shares': typeof ApiSharesRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/api/learning/analytics': typeof ApiLearningAnalyticsRoute
  '/api/learning/features': typeof ApiLearningFeaturesRoute
  '/api/learning/flashcards': typeof ApiLearningFlashcardsRoute
  '/api/learning/goals': typeof ApiLearningGoalsRoute
  '/api/learning/memory': typeof ApiLearningMemoryRoute
  '/api/learning/notes': typeof ApiLearningNotesRoute
  '/api/learning/ocr': typeof ApiLearningOcrRoute
  '/api/learning/revision': typeof ApiLearningRevisionRoute
  '/api/learning/session': typeof ApiLearningSessionRoute
  '/api/learning/voice': typeof ApiLearningVoiceRoute
  '/api/learning/whiteboard': typeof ApiLearningWhiteboardRoute
  '/api/shared/$token': typeof ApiSharedTokenRoute
  '/api/shares/$token': typeof ApiSharesTokenRoute
  '/api/learning/sources/ingest': typeof ApiLearningSourcesIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/boards'
    | '/calendar'
    | '/chat'
    | '/documents'
    | '/feed'
    | '/learn'
    | '/memory'
    | '/plan'
    | '/practice'
    | '/productivity'
    | '/progress'
    | '/settings'
    | '/statistics'
    | '/study'
    | '/tasks'
    | '/voice'
    | '/api/chat'
    | '/api/health'
    | '/api/openrouter-test'
    | '/api/shares'
    | '/share/$token'
    | '/api/learning/analytics'
    | '/api/learning/features'
    | '/api/learning/flashcards'
    | '/api/learning/goals'
    | '/api/learning/memory'
    | '/api/learning/notes'
    | '/api/learning/ocr'
    | '/api/learning/revision'
    | '/api/learning/session'
    | '/api/learning/voice'
    | '/api/learning/whiteboard'
    | '/api/shared/$token'
    | '/api/shares/$token'
    | '/api/learning/sources/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/boards'
    | '/calendar'
    | '/chat'
    | '/documents'
    | '/feed'
    | '/learn'
    | '/memory'
    | '/plan'
    | '/practice'
    | '/productivity'
    | '/progress'
    | '/settings'
    | '/statistics'
    | '/study'
    | '/tasks'
    | '/voice'
    | '/api/chat'
    | '/api/health'
    | '/api/openrouter-test'
    | '/api/shares'
    | '/share/$token'
    | '/api/learning/analytics'
    | '/api/learning/features'
    | '/api/learning/flashcards'
    | '/api/learning/goals'
    | '/api/learning/memory'
    | '/api/learning/notes'
    | '/api/learning/ocr'
    | '/api/learning/revision'
    | '/api/learning/session'
    | '/api/learning/voice'
    | '/api/learning/whiteboard'
    | '/api/shared/$token'
    | '/api/shares/$token'
    | '/api/learning/sources/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/boards'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/documents'
    | '/_authenticated/feed'
    | '/_authenticated/learn'
    | '/_authenticated/memory'
    | '/_authenticated/plan'
    | '/_authenticated/practice'
    | '/_authenticated/productivity'
    | '/_authenticated/progress'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/study'
    | '/_authenticated/tasks'
    | '/_authenticated/voice'
    | '/api/chat'
    | '/api/health'
    | '/api/openrouter-test'
    | '/api/shares'
    | '/share/$token'
    | '/api/learning/analytics'
    | '/api/learning/features'
    | '/api/learning/flashcards'
    | '/api/learning/goals'
    | '/api/learning/memory'
    | '/api/learning/notes'
    | '/api/learning/ocr'
    | '/api/learning/revision'
    | '/api/learning/session'
    | '/api/learning/voice'
    | '/api/learning/whiteboard'
    | '/api/shared/$token'
    | '/api/shares/$token'
    | '/api/learning/sources/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOpenrouterTestRoute: typeof ApiOpenrouterTestRoute
  ApiSharesRoute: typeof ApiSharesRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
  ApiLearningAnalyticsRoute: typeof ApiLearningAnalyticsRoute
  ApiLearningFeaturesRoute: typeof ApiLearningFeaturesRoute
  ApiLearningFlashcardsRoute: typeof ApiLearningFlashcardsRoute
  ApiLearningGoalsRoute: typeof ApiLearningGoalsRoute
  ApiLearningMemoryRoute: typeof ApiLearningMemoryRoute
  ApiLearningNotesRoute: typeof ApiLearningNotesRoute
  ApiLearningOcrRoute: typeof ApiLearningOcrRoute
  ApiLearningRevisionRoute: typeof ApiLearningRevisionRoute
  ApiLearningSessionRoute: typeof ApiLearningSessionRoute
  ApiLearningVoiceRoute: typeof ApiLearningVoiceRoute
  ApiLearningWhiteboardRoute: typeof ApiLearningWhiteboardRoute
  ApiSharedTokenRoute: typeof ApiSharedTokenRoute
  ApiLearningSourcesIngestRoute: typeof ApiLearningSourcesIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shares': {
      id: '/api/shares'
      path: '/api/shares'
      fullPath: '/api/shares'
      preLoaderRoute: typeof ApiSharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-test': {
      id: '/api/openrouter-test'
      path: '/api/openrouter-test'
      fullPath: '/api/openrouter-test'
      preLoaderRoute: typeof ApiOpenrouterTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study': {
      id: '/_authenticated/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AuthenticatedStudyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity': {
      id: '/_authenticated/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof AuthenticatedProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boards': {
      id: '/_authenticated/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AuthenticatedBoardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/shares/$token': {
      id: '/api/shares/$token'
      path: '/$token'
      fullPath: '/api/shares/$token'
      preLoaderRoute: typeof ApiSharesTokenRouteImport
      parentRoute: typeof ApiSharesRoute
    }
    '/api/shared/$token': {
      id: '/api/shared/$token'
      path: '/api/shared/$token'
      fullPath: '/api/shared/$token'
      preLoaderRoute: typeof ApiSharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/whiteboard': {
      id: '/api/learning/whiteboard'
      path: '/api/learning/whiteboard'
      fullPath: '/api/learning/whiteboard'
      preLoaderRoute: typeof ApiLearningWhiteboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/voice': {
      id: '/api/learning/voice'
      path: '/api/learning/voice'
      fullPath: '/api/learning/voice'
      preLoaderRoute: typeof ApiLearningVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/session': {
      id: '/api/learning/session'
      path: '/api/learning/session'
      fullPath: '/api/learning/session'
      preLoaderRoute: typeof ApiLearningSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/revision': {
      id: '/api/learning/revision'
      path: '/api/learning/revision'
      fullPath: '/api/learning/revision'
      preLoaderRoute: typeof ApiLearningRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/ocr': {
      id: '/api/learning/ocr'
      path: '/api/learning/ocr'
      fullPath: '/api/learning/ocr'
      preLoaderRoute: typeof ApiLearningOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/notes': {
      id: '/api/learning/notes'
      path: '/api/learning/notes'
      fullPath: '/api/learning/notes'
      preLoaderRoute: typeof ApiLearningNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/memory': {
      id: '/api/learning/memory'
      path: '/api/learning/memory'
      fullPath: '/api/learning/memory'
      preLoaderRoute: typeof ApiLearningMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/goals': {
      id: '/api/learning/goals'
      path: '/api/learning/goals'
      fullPath: '/api/learning/goals'
      preLoaderRoute: typeof ApiLearningGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/flashcards': {
      id: '/api/learning/flashcards'
      path: '/api/learning/flashcards'
      fullPath: '/api/learning/flashcards'
      preLoaderRoute: typeof ApiLearningFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/features': {
      id: '/api/learning/features'
      path: '/api/learning/features'
      fullPath: '/api/learning/features'
      preLoaderRoute: typeof ApiLearningFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/analytics': {
      id: '/api/learning/analytics'
      path: '/api/learning/analytics'
      fullPath: '/api/learning/analytics'
      preLoaderRoute: typeof ApiLearningAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/learning/sources/ingest': {
      id: '/api/learning/sources/ingest'
      path: '/api/learning/sources/ingest'
      fullPath: '/api/learning/sources/ingest'
      preLoaderRoute: typeof ApiLearningSourcesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBoardsRoute: typeof AuthenticatedBoardsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedProductivityRoute: typeof AuthenticatedProductivityRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedStudyRoute: typeof AuthenticatedStudyRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBoardsRoute: AuthenticatedBoardsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedProductivityRoute: AuthenticatedProductivityRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedStudyRoute: AuthenticatedStudyRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiSharesRouteChildren {
  ApiSharesTokenRoute: typeof ApiSharesTokenRoute
}

const ApiSharesRouteChildren: ApiSharesRouteChildren = {
  ApiSharesTokenRoute: ApiSharesTokenRoute,
}

const ApiSharesRouteWithChildren = ApiSharesRoute._addFileChildren(
  ApiSharesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOpenrouterTestRoute: ApiOpenrouterTestRoute,
  ApiSharesRoute: ApiSharesRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
  ApiLearningAnalyticsRoute: ApiLearningAnalyticsRoute,
  ApiLearningFeaturesRoute: ApiLearningFeaturesRoute,
  ApiLearningFlashcardsRoute: ApiLearningFlashcardsRoute,
  ApiLearningGoalsRoute: ApiLearningGoalsRoute,
  ApiLearningMemoryRoute: ApiLearningMemoryRoute,
  ApiLearningNotesRoute: ApiLearningNotesRoute,
  ApiLearningOcrRoute: ApiLearningOcrRoute,
  ApiLearningRevisionRoute: ApiLearningRevisionRoute,
  ApiLearningSessionRoute: ApiLearningSessionRoute,
  ApiLearningVoiceRoute: ApiLearningVoiceRoute,
  ApiLearningWhiteboardRoute: ApiLearningWhiteboardRoute,
  ApiSharedTokenRoute: ApiSharedTokenRoute,
  ApiLearningSourcesIngestRoute: ApiLearningSourcesIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
